{"author":"dotnet-bot","ms.author":"dotnetcontent","manager":"wpickett","breadcrumb_path":"/dotnet/toc.json","ms.topic":"managed-reference","ms.prod":".net","search.ms_sitename":"Docs","search.ms_docsetname":"docs-internal","version":0,"locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","depot_name":"MSDN.docs-internal","original_ref_skeleton_git_url":"https://github.com/dotnet/docs-internal/blob/master/api/System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.yml","open_to_public_contributors":false,"api_name":["System.Activities.WorkflowApplicationUnhandledExceptionEventArgs","System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource","System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId","System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException"],"api_location":["System.Activities.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Activities.WorkflowApplicationUnhandledExceptionEventArgs","System::Activities::WorkflowApplicationUnhandledExceptionEventArgs","System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSource","System::Activities::WorkflowApplicationUnhandledExceptionEventArgs::ExceptionSource","System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.ExceptionSourceInstanceId","System::Activities::WorkflowApplicationUnhandledExceptionEventArgs::ExceptionSourceInstanceId","System.Activities.WorkflowApplicationUnhandledExceptionEventArgs.UnhandledException","System::Activities::WorkflowApplicationUnhandledExceptionEventArgs::UnhandledException"],"dev_langs":["csharp"],"updated_at":"2017-03-24 01:41 AM","document_id":"b91c371a-8492-87c1-50f5-1538cb45383d","content_git_url":"https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationUnhandledExceptionEventArgs.xml","layout":"Reference","pagetype":"Reference","title":"WorkflowApplicationUnhandledExceptionEventArgs class | Microsoft Docs","description":"Provides information about an unhandled exception that occurred in a workflow instance.\n","toc_asset_id":"api/_splitted/System.Activities/toc.json","toc_rel":"_splitted/System.Activities/toc.json","source_url":"","ms.assetid":"System.Activities.WorkflowApplicationUnhandledExceptionEventArgs","canonical_url":"https://ppe.docs.microsoft.com/en-us/dotnet/api/system.activities.workflowapplicationunhandledexceptioneventargs","is_dynamic_rendering":true,"content_type":"application/json","publish_version":"{\"opbuild.templates.docs\":\"1.29.3\",\"commit_id\":\"b3a23883507f33cbc5269a49bae8b286e3a2a4b9\",\"branch\":\"master\",\"opbuild.scripts\":\"1.29.3\",\"opbuild.htmltopdftool\":\"1.29.3\",\"opbuild.gitcontributorinformationresolver\":\"1.29.3\",\"opbuild_service\":\"1.29.125.0\",\"docfx.console\":\"2.14.1\",\"opbuild.resolvedependencyconsole\":\"1.29.3\",\"opbuild.schemavalidationconsole\":\"1.29.3\",\"opbuild.redirectionresolver\":\"1.29.3\",\"opbuild.templates.intellisense\":\"1.29.3\",\"dependencies\":[{\"branch\":\"preview\",\"path\":\"_themes\",\"url\":\"https://github.com/Microsoft/templates.docs.msft\",\"commit_id\":\"29e90ce5b9d5929c589caa705c6513cef19b8b33\",\"opbuild.templates.common\":\"1.29.3\"},{\"branch\":\"master\",\"path\":\"_themes.pdf\",\"url\":\"https://github.com/Microsoft/templates.docs.msft.pdf\",\"commit_id\":\"b2158fbf2c62f32aff19e6f61397f4caa40b05f7\",\"opbuild.templates.common\":\"1.29.3\"}]}"}