{"author":"dotnet-bot","ms.author":"dotnetcontent","manager":"wpickett","breadcrumb_path":"/dotnet-internal/toc.json","ms.topic":"managed-reference","ms.prod":".net","search.ms_sitename":"Docs","search.ms_docsetname":"docs-internal","version":0,"locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","depot_name":"MSDN.docs-internal","original_ref_skeleton_git_url":"https://github.com/dotnet/docs-internal/blob/master/api/System.Data.Services.DataServiceException.yml","open_to_public_contributors":false,"api_name":["System.Data.Services.DataServiceException","System.Data.Services.DataServiceException..ctor","System.Data.Services.DataServiceException.ErrorCode","System.Data.Services.DataServiceException.GetObjectData","System.Data.Services.DataServiceException.MessageLanguage","System.Data.Services.DataServiceException.StatusCode"],"api_location":["System.Data.Services.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Data.Services.DataServiceException","System::Data::Services::DataServiceException","System.Data.Services.DataServiceException.#ctor","System::Data::Services::DataServiceException::#ctor","System.Data.Services.DataServiceException.ErrorCode","System::Data::Services::DataServiceException::ErrorCode","System.Data.Services.DataServiceException.GetObjectData","System::Data::Services::DataServiceException::GetObjectData","System.Data.Services.DataServiceException.MessageLanguage","System::Data::Services::DataServiceException::MessageLanguage","System.Data.Services.DataServiceException.StatusCode","System::Data::Services::DataServiceException::StatusCode"],"dev_langs":["csharp"],"updated_at":"2017-03-22 03:41 AM","document_id":"31154288-7d7c-dcb7-3375-6c66fe4ee599","content_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/xml/System.Data.Services/DataServiceException.xml","layout":"Reference","pagetype":"Reference","title":"DataServiceException class | Microsoft Docs","description":"Represents an instance of the DataServiceException class with a specified message that describes the error.\n","toc_asset_id":"api/_splitted/System.Data.Services/toc.json","toc_rel":"_splitted/System.Data.Services/toc.json","source_url":"","ms.assetid":"System.Data.Services.DataServiceException","canonical_url":"https://ppe.docs.microsoft.com/en-us/dotnet-all/api/system.data.services.dataserviceexception","is_dynamic_rendering":true,"content_type":"application/json","publish_version":"{\"opbuild.templates.docs\":\"1.29.1\",\"commit_id\":\"0a04257e5c242f6ef12ecbb3f3d558f8ee4e0552\",\"branch\":\"master\",\"opbuild.scripts\":\"1.29.1\",\"opbuild.htmltopdftool\":\"1.29.1\",\"opbuild.gitcontributorinformationresolver\":\"1.29.1\",\"opbuild_service\":\"1.29.121.0\",\"docfx.console\":\"2.14.1\",\"opbuild.resolvedependencyconsole\":\"1.29.1\",\"opbuild.schemavalidationconsole\":\"1.29.1\",\"opbuild.redirectionresolver\":\"1.29.1\",\"opbuild.templates.intellisense\":\"1.29.1\",\"dependencies\":[{\"branch\":\"preview\",\"path\":\"_themes\",\"url\":\"https://github.com/Microsoft/templates.docs.msft\",\"commit_id\":\"bd3ce9826a7b70f96ae3e9981c91aa0b12bc12ad\",\"opbuild.templates.common\":\"1.29.1\"},{\"branch\":\"master\",\"path\":\"_themes.pdf\",\"url\":\"https://github.com/Microsoft/templates.docs.msft.pdf\",\"commit_id\":\"b2158fbf2c62f32aff19e6f61397f4caa40b05f7\",\"opbuild.templates.common\":\"1.29.1\"}]}"}